# Generated by Django 5.0.2 on 2024-03-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_person_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person'},
        ),
    ]
